# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

TestGeneric <- function(lot, machine, population = 5000L, loop = 500L, crossover = 1., mutation = 0.2) {
    .Call('SimSemi_TestGeneric', PACKAGE = 'SimSemi', lot, machine, population, loop, crossover, mutation)
}

TestHeuristic <- function(lot, machine, population = 5000L, loop = 500L) {
    .Call('SimSemi_TestHeuristic', PACKAGE = 'SimSemi', lot, machine, population, loop)
}

